export type Locale = 'en' | 'es';
export const property = { name: 'Villa Tortuga', guests: 10, bedrooms: 4, beds: 5, bathrooms: 4, airbnb: 'https://www.airbnb.com/rooms/1516054436387600999', reviews: 'https://www.airbnb.com/rooms/1516054436387600999/reviews', rating: '5.0', host: { name: 'Roxana', photo: '/people/roxana.webp', isSuperhost: true, reviewCount: 38, rating: '5.0', yearsHosting: 3 } } as const;
export const categories = [
 ['Living room','Sala'],['Kitchen','Cocina'],['Primary suite','Suite principal'],['Bedroom 2','Dormitorio 2'],['Bedroom 3','Dormitorio 3'],['Bedroom 4','Dormitorio 4'],['Bathroom 1','Baño 1'],['Bathroom 2','Baño 2'],['Bathroom 3','Baño 3'],['Bathroom 4','Baño 4'],['Balcony','Balcón'],['Laundry','Lavandería'],['Exterior','Exterior'],['Pool','Piscina'],['Optional dock','Muelle opcional']
] as const;
export const copy = {
 en: {
  skip:'Skip to content', nav:['The villa','Spaces','Gallery','Culebra','Your stay'], book:'Check availability on Airbnb', shortBook:'Check availability', external:'opens Airbnb in a new tab', language:'Español', menu:'Menu', close:'Close',
  eyebrow:'A PRIVATE VILLA · CULEBRA, PUERTO RICO', hero:'A little closer\nto the horizon.', heroText:'Ocean views. Unhurried days. Your own private escape.', explore:'Discover the villa', facts:['Guests','Bedrooms','Beds','Bathrooms'],
  introLabel:'WELCOME TO VILLA TORTUGA', introTitle:'An island escape.\nWhere time slows down.', intro:'Above the blue waters of Culebra, a home made for being together. Open terraces, light-filled rooms, and a private heated pool invite you to settle into a slower rhythm.', introSmall:'Four bedrooms across two levels. Space to gather, and a quiet corner to call your own.',
  poolLabel:'OUTSIDE, AT YOUR OWN PACE', poolTitle:'Every moment comes\nwith a view.', poolText:'A morning swim. A long lunch by the pool. Coffee on the upper balcony, with the ocean stretching out before you. Here, simple pleasures become the best memories.', poolDetail:'Private heated pool · Panoramic terraces · Outdoor dining',
  roomLabel:'REST COMES NATURALLY', roomTitle:'Four rooms.\nYour own kind of quiet.', roomIntro:'Two king beds and three queen beds, thoughtfully arranged for up to ten guests. Every bedroom includes air conditioning and a Smart TV.',
  rooms:[['The primary suite','MAIN LEVEL · KING BED','A private bathroom and a terrace of your own.'],['Bedroom two','MAIN LEVEL · KING BED','Space to unwind. Shares the full hallway bathroom with bedroom three.'],['Bedroom three','MAIN LEVEL · QUEEN BED','A restful retreat, with the full hallway bathroom shared with bedroom two.'],['The ground-floor retreat','GROUND FLOOR · TWO QUEEN BEDS','A private bathroom, kitchenette and private terrace.']],
  kitchenLabel:'GOOD FOOD, GOOD COMPANY', kitchenTitle:'Stay in.\nMake something together.', kitchenText:'A full kitchen, coffee makers and everyday cooking essentials make it easy to feel at home. Gather at the island, share a meal inside, or take dinner out to the poolside table for eight.',
  galleryLabel:'A CLOSER LOOK', galleryTitle:'Picture your days here.', galleryText:'Explore the spaces, from the first morning coffee to the last look at the sea.', all:'All spaces', more:'Show more photos', view:'Open photo', previous:'Previous photo', next:'Next photo', galleryClose:'Close gallery', photo:'Photo', of:'of', imageError:'This photo is unavailable. Continue to the next photo.',
  amenitiesLabel:'THOUGHTFULLY EQUIPPED', amenitiesTitle:'Everything for settling in.', amenitiesMore:'Explore all amenities',
  amenityGroups:[['Everyday comfort','Air conditioning','Wi-Fi','Smart TVs & sound system','Board games'],['Kitchen & dining','Full kitchen & dishwasher','Espresso & drip coffee makers','Cookware & tableware','Outdoor dining & BBQ'],['A lighter suitcase','Washer & dryer','Linens & towels','Hair dryer & bathroom essentials','Beach chairs & cooler'],['Easy arrivals','Free on-site parking','Smart-lock self check-in','Private entrance','Private balconies & terraces']],
  locationLabel:'18° NORTH. A DIFFERENT PACE.', locationTitle:'A little island.\nSo much to explore.', locationText:'Culebra’s green hills and blue waters set the scene. Spend the day at Zoni Beach, explore the island, and return to the comfort and views of Villa Tortuga.', zoni:'Zoni Beach', zoniTime:'About 6 minutes', town:'Town', townTime:'About 15–18 minutes', flamenco:'Flamenco Beach', flamencoTime:'Around 15 minutes away', locationNote:'Approximate travel times reported in the Airbnb listing. A rental vehicle is strongly recommended. The exact address is shared with confirmed guests.',
  extrasTitle:'Your stay, thoughtfully curated.', extrasText:'Our concierge team can coordinate private boat trips, guided snorkeling, fishing charters, introductory scuba, in-villa massages, private yoga, grocery provisioning, housekeeping, and optional private dock access. All services require advance notice, are subject to availability, and incur additional fees.',
  reviewsLabel:'GUEST PERSPECTIVES', reviewsTitle:'In Their Own Words.', ratingLabel:'AIRBNB GUEST RATING', reviewRating:'5.0/5 based on 28 Airbnb reviews.', reviewSummary:'Editorial summaries of public Airbnb reviews; not direct quotations.', reviewsRegion:'Guest review highlights', readReviews:'Read the original reviews on Airbnb', airbnbEmbedLabel:'THE ORIGINAL LISTING', airbnbEmbedTitle:'Continue on Airbnb.', airbnbEmbedText:'Current availability, rates and booking details remain on Airbnb.', airbnbEmbedAction:'View Villa Tortuga on Airbnb',
  reviews:[['Aaron','Family stay','Memorable views, everything the group needed, and thoughtful help before and throughout the trip.'],['Maureen','Family stay','Spacious rooms, a well-equipped kitchen, and a peaceful setting with an exceptional ocean view.'],['Elliot','Family stay','Room for eight to gather, dine outdoors, and make the terrace a favorite place to relax.'],['Kelly','Group trip','Beautiful views, a clean pool, comfortable interiors, and attentive hosting from arrival to departure.']],
  hostLabel:'YOUR HOST', hostTitle:'A warm welcome,\nwith local knowledge.', hostText:'Roxana hosts Villa Tortuga and speaks English and Spanish. For questions about the villa or help planning your stay, connect with her through the Airbnb listing.', hostAction:'Meet Roxana on Airbnb', hostSuperhost:'Superhost', hostStats:['Reviews','Rating','Years hosting'], hostSource:'Airbnb profile snapshot · September 18, 2026',
  important:'The villa uses collected rainwater. Please conserve water during your stay.',
  faqTitle:'A few things to know.', faqs:[['When are check-in and check-out?','Check-in is after 3 pm; check-out is before 11 am. Self check-in uses a smart lock.'],['Is the pool heated?','Yes. The pool is heated and set to a comfortable temperature. Guests cannot adjust it directly, but feel free to contact your host if you prefer a different temperature.'],['Is the entire home private?','The home is reserved for your group. Maintenance staff may occasionally access outdoor and green areas.'],['Can children stay?','Please confirm the current age policy and suitability of the pool, stairs and terraces directly with the host before booking.'],['Is the dock included?','No. Dock access is optional, subject to availability, prior approval and an additional fee. Ask the host about access and vessel requirements.'],['What are the rates and cancellation policy?','Current prices, availability, minimum stays and cancellation conditions are shown on Airbnb for your selected dates.']],
  finalLabel:'YOUR CULEBRA CHAPTER', finalTitle:'Leave a little room\nfor island time.', finalText:'Find your dates. Bring your people. Make yourself at home.', footer:'A private island stay in Culebra, Puerto Rico.', top:'Back to top', notFound:'This page has drifted away.', home:'Return to the villa', title:'Villa Tortuga | Private Oceanview Villa in Culebra', description:'A private four-bedroom villa in Culebra, Puerto Rico, for up to 10 guests. Panoramic ocean views, a heated pool and room to unwind near Zoni Beach.'
 },
 es: {
  skip:'Saltar al contenido', nav:['La villa','Espacios','Galería','Culebra','Tu estadía'], book:'Consultar disponibilidad en Airbnb', shortBook:'Consultar disponibilidad', external:'abre Airbnb en una pestaña nueva', language:'English', menu:'Menú', close:'Cerrar',
  eyebrow:'UNA VILLA PRIVADA · CULEBRA, PUERTO RICO', hero:'Un poco más cerca\ndel horizonte.', heroText:'Vistas al mar. Días sin prisa. Su propia escapada privada.', explore:'Conocer la villa', facts:['Huéspedes','Dormitorios','Camas','Baños'],
  introLabel:'BIENVENIDOS A VILLA TORTUGA', introTitle:'Una escapada a la isla.\nDonde el tiempo transcurre más despacio.', intro:'Sobre las aguas azules de Culebra, una casa pensada para compartir. Terrazas abiertas, habitaciones luminosas y una piscina privada climatizada invitan a disfrutar de otro ritmo.', introSmall:'Cuatro dormitorios en dos niveles. Espacios para reunirse y un rincón tranquilo para cada quien.',
  poolLabel:'AL AIRE LIBRE, A SU RITMO', poolTitle:'Cada momento viene\ncon una vista.', poolText:'Un baño por la mañana. Un almuerzo largo junto a la piscina. Café en el balcón superior, con el mar de fondo. Aquí, los placeres sencillos se convierten en los mejores recuerdos.', poolDetail:'Piscina privada climatizada · Terrazas panorámicas · Comedor exterior',
  roomLabel:'DESCANSAR SE SIENTE NATURAL', roomTitle:'Cuatro habitaciones.\nSu propia tranquilidad.', roomIntro:'Dos camas king y tres queen, distribuidas para recibir hasta diez huéspedes. Todos los dormitorios cuentan con aire acondicionado y Smart TV.',
  rooms:[['La suite principal','NIVEL PRINCIPAL · CAMA KING','Baño privado y una terraza propia.'],['Dormitorio dos','NIVEL PRINCIPAL · CAMA KING','Espacio para descansar. Comparte el baño completo del pasillo con el dormitorio tres.'],['Dormitorio tres','NIVEL PRINCIPAL · CAMA QUEEN','Un refugio tranquilo. Comparte el baño completo del pasillo con el dormitorio dos.'],['El refugio de la planta baja','PLANTA BAJA · DOS CAMAS QUEEN','Baño privado, kitchenette y terraza privada.']],
  kitchenLabel:'BUENA COMIDA, BUENA COMPAÑÍA', kitchenTitle:'Quédense en casa.\nCocinen juntos.', kitchenText:'La cocina completa, las cafeteras y los artículos básicos para cocinar hacen fácil sentirse en casa. Compartan en la isla de cocina, coman adentro o lleven la cena a la mesa exterior para ocho personas.',
  galleryLabel:'UNA MIRADA MÁS CERCANA', galleryTitle:'Imaginen sus días aquí.', galleryText:'Recorran los espacios, desde el primer café hasta la última mirada al mar.', all:'Todos los espacios', more:'Ver más fotos', view:'Abrir foto', previous:'Foto anterior', next:'Foto siguiente', galleryClose:'Cerrar galería', photo:'Foto', of:'de', imageError:'Esta foto no está disponible. Continúa a la siguiente.',
  amenitiesLabel:'TODO EN SU LUGAR', amenitiesTitle:'Comodidad para quedarse.', amenitiesMore:'Ver todas las comodidades',
  amenityGroups:[['Comodidad diaria','Aire acondicionado','Wi-Fi','Smart TVs y sistema de sonido','Juegos de mesa'],['Cocina y comedor','Cocina completa y lavaplatos','Cafeteras de espresso y goteo','Utensilios y vajilla','Comedor exterior y BBQ'],['Viajen más ligeros','Lavadora y secadora','Ropa de cama y toallas','Secador y artículos de baño','Sillas de playa y neverita portátil'],['Llegar es sencillo','Estacionamiento gratuito','Check-in con cerradura inteligente','Entrada privada','Balcones y terrazas privados']],
  locationLabel:'18° NORTE. OTRO RITMO.', locationTitle:'Una pequeña isla.\nTanto por explorar.', locationText:'Las colinas verdes y las aguas azules de Culebra crean el escenario. Pasen el día en Playa Zoni, exploren la isla y regresen a la comodidad y las vistas de Villa Tortuga.', zoni:'Playa Zoni', zoniTime:'Unos 6 minutos', town:'El pueblo', townTime:'Unos 15–18 minutos', flamenco:'Playa Flamenco', flamencoTime:'A unos 15 minutos', locationNote:'Tiempos aproximados indicados en el anuncio de Airbnb. Se recomienda alquilar un vehículo. La dirección exacta se comparte con huéspedes confirmados.',
  extrasTitle:'Su estadía, cuidadosamente planeada.', extrasText:'Nuestro equipo de concierge puede coordinar paseos privados en bote, snorkeling guiado, charters de pesca, buceo introductorio, masajes en la villa, yoga privado, abastecimiento de comestibles, limpieza y acceso opcional a un muelle privado. Todos los servicios requieren aviso previo, están sujetos a disponibilidad y tienen cargos adicionales.',
  reviewsLabel:'EXPERIENCIAS DE HUÉSPEDES', reviewsTitle:'En sus propias palabras.', ratingLabel:'CALIFICACIÓN DE HUÉSPEDES EN AIRBNB', reviewRating:'5.0/5 basado en 28 reseñas de Airbnb.', reviewSummary:'Síntesis editoriales de reseñas públicas de Airbnb; no son citas textuales.', reviewsRegion:'Comentarios destacados de huéspedes', readReviews:'Leer las reseñas originales en Airbnb', airbnbEmbedLabel:'EL ANUNCIO ORIGINAL', airbnbEmbedTitle:'Continúen en Airbnb.', airbnbEmbedText:'La disponibilidad, las tarifas y los detalles de reserva vigentes permanecen en Airbnb.', airbnbEmbedAction:'Ver Villa Tortuga en Airbnb',
  reviews:[['Aaron','Estadía familiar','Vistas memorables, todo lo necesario para el grupo y atención antes y durante el viaje.'],['Maureen','Estadía familiar','Habitaciones amplias, cocina bien equipada y un entorno tranquilo con una vista excepcional al mar.'],['Elliot','Estadía familiar','Espacio para que ocho personas compartan, coman al aire libre y disfruten la terraza como su rincón favorito.'],['Kelly','Viaje grupal','Vistas hermosas, piscina limpia, interiores cómodos y atención desde la llegada hasta la salida.']],
  hostLabel:'SU ANFITRIONA', hostTitle:'Una bienvenida cálida,\ncon conocimiento local.', hostText:'Roxana es la anfitriona de Villa Tortuga y habla inglés y español. Para consultar sobre la villa o planificar su estadía, contáctenla mediante el anuncio de Airbnb.', hostAction:'Conocer a Roxana en Airbnb', hostSuperhost:'Superanfitriona', hostStats:['Reseñas','Calificación','Años hospedando'], hostSource:'Perfil de Airbnb · 18 de septiembre de 2026',
  important:'La villa utiliza agua de lluvia recolectada. Por favor, conserven agua durante su estadía.',
  faqTitle:'Algunas cosas que saber.', faqs:[['¿Cuáles son los horarios de entrada y salida?','La entrada es después de las 3 p. m. y la salida antes de las 11 a. m. El check-in autónomo utiliza una cerradura inteligente.'],['¿La piscina es climatizada?','Sí. La piscina está climatizada y configurada a una temperatura cómoda. Los huéspedes no pueden ajustarla directamente, pero pueden comunicarse con su anfitriona si prefieren una temperatura diferente.'],['¿La casa es completamente privada?','La casa queda reservada para su grupo. El personal de mantenimiento puede acceder ocasionalmente a áreas exteriores y verdes.'],['¿Pueden hospedarse niños?','Antes de reservar, confirmen con la anfitriona la política de edad vigente y si la piscina, escaleras y terrazas son adecuadas para su grupo.'],['¿El muelle está incluido?','No. Es opcional, sujeto a disponibilidad, aprobación previa y un cargo adicional. Consulten el acceso y los requisitos de la embarcación.'],['¿Cuáles son las tarifas y la política de cancelación?','Airbnb muestra los precios, disponibilidad, estadía mínima y condiciones de cancelación vigentes para las fechas seleccionadas.']],
  finalLabel:'SU PRÓXIMA HISTORIA EN CULEBRA', finalTitle:'Dejen espacio\npara la vida en la isla.', finalText:'Elijan sus fechas. Reúnan a los suyos. Siéntanse en casa.', footer:'Una estadía privada en Culebra, Puerto Rico.', top:'Volver arriba', notFound:'Esta página se fue con la marea.', home:'Volver a la villa', title:'Villa Tortuga | Villa privada con vista al mar en Culebra', description:'Villa privada de cuatro dormitorios en Culebra, Puerto Rico, para hasta 10 huéspedes. Vistas panorámicas, piscina climatizada y descanso cerca de Playa Zoni.'
 }
} as const;
export type Copy = typeof copy[Locale];
