export type Locale = 'en' | 'es';
export const property = { name: 'Villa Tortuga', guests: 10, bedrooms: 4, beds: 5, bathrooms: 4, airbnb: 'https://www.airbnb.com/rooms/1516054436387600999', reviews: 'https://www.airbnb.com/rooms/1516054436387600999/reviews', observedAt: '2026-09-17', rating: '5.0', reviewCount: 28 } as const;
export const categories = [
 ['Living room','Sala'],['Kitchen','Cocina'],['Primary suite','Suite principal'],['Bedroom 2','Dormitorio 2'],['Bedroom 3','Dormitorio 3'],['Bedroom 4','Dormitorio 4'],['Bathroom 1','Baño 1'],['Bathroom 2','Baño 2'],['Bathroom 3','Baño 3'],['Bathroom 4','Baño 4'],['Balcony','Balcón'],['Laundry','Lavandería'],['Exterior','Exterior'],['Pool','Piscina'],['Optional dock','Muelle opcional']
] as const;
export const copy = {
 en: {
  skip:'Skip to content', nav:['The villa','Spaces','Gallery','Culebra','Your stay'], book:'Check availability on Airbnb', shortBook:'Check availability', external:'opens Airbnb in a new tab', language:'Español', menu:'Menu', close:'Close',
  eyebrow:'A PRIVATE VILLA · CULEBRA, PUERTO RICO', hero:'A little closer\nto the horizon.', heroText:'Ocean views. Unhurried days. A place all your own.', explore:'Discover the villa', facts:['Guests','Bedrooms','Beds','Bathrooms'],
  introLabel:'WELCOME TO VILLA TORTUGA', introTitle:'An island escape.\nRoom for everyone.', intro:'Above the blue waters of Culebra, a home made for being together. Open terraces, light-filled rooms, and a private heated pool invite you to settle into a slower rhythm.', introSmall:'Four bedrooms across two levels. Space to gather, and a quiet corner to call your own.',
  poolLabel:'OUTSIDE, AT YOUR OWN PACE', poolTitle:'The view is\nalways with you.', poolText:'A morning swim. A long lunch by the pool. Coffee on the upper balcony, with the ocean stretching out before you. Here, the best plans leave a little room for doing nothing.', poolDetail:'Private heated pool · Panoramic terraces · Outdoor dining',
  roomLabel:'REST COMES NATURALLY', roomTitle:'Four rooms.\nYour own kind of quiet.', roomIntro:'Two king beds and three queen beds, thoughtfully arranged for up to ten guests. Every bedroom includes air conditioning and a Smart TV.',
  rooms:[['The primary suite','MAIN LEVEL · KING BED','A private bathroom and a terrace of your own.'],['Bedroom two','MAIN LEVEL · KING BED','Space to unwind. Shares the full hallway bathroom with bedroom three.'],['Bedroom three','MAIN LEVEL · QUEEN BED','A restful retreat, with the full hallway bathroom shared with bedroom two.'],['The ground-floor retreat','GROUND FLOOR · TWO QUEEN BEDS','A private bathroom, kitchenette and private terrace.']],
  kitchenLabel:'GOOD FOOD, GOOD COMPANY', kitchenTitle:'Stay in.\nMake something together.', kitchenText:'A full kitchen, coffee makers and everyday cooking essentials make it easy to feel at home. Gather at the island, share a meal inside, or take dinner out to the poolside table for eight.',
  galleryLabel:'A CLOSER LOOK', galleryTitle:'Picture your days here.', galleryText:'Explore the spaces, from the first morning coffee to the last look at the sea.', all:'All spaces', more:'Show more photos', view:'Open photo', previous:'Previous photo', next:'Next photo', galleryClose:'Close gallery', photo:'Photo', of:'of', imageError:'This photo is unavailable. Continue to the next photo.',
  amenitiesLabel:'THOUGHTFULLY EQUIPPED', amenitiesTitle:'Everything for settling in.', amenitiesMore:'Explore all amenities',
  amenityGroups:[['Everyday comfort','Air conditioning','Wi-Fi','Smart TVs & sound system','Board games'],['Kitchen & dining','Full kitchen & dishwasher','Espresso & drip coffee makers','Cookware & tableware','Outdoor dining & BBQ'],['A lighter suitcase','Washer & dryer','Linens & towels','Hair dryer & bathroom essentials','Beach chairs & cooler'],['Easy arrivals','Free on-site parking','Smart-lock self check-in','Private entrance','Private balconies & terraces']],
  locationLabel:'18° NORTH. A DIFFERENT PACE.', locationTitle:'A little island.\nA world away.', locationText:'Culebra’s green hills and open sea frame your stay. Head to Zoni Beach, explore the island, or simply come back to your own view.', zoni:'Zoni Beach', zoniTime:'About 6 minutes', town:'Town', townTime:'About 15–18 minutes', locationNote:'Approximate travel times reported in the Airbnb listing. A rental vehicle is strongly recommended. The exact address is shared with confirmed guests.',
  extrasTitle:'A stay shaped around you.', extrasText:'Ask ahead about boat trips, guided snorkeling, introductory scuba, massage, private yoga, grocery provisioning and housekeeping. Optional private dock access may also be available. All require advance coordination, availability confirmation and additional fees.',
  reviewsLabel:'GUEST PERSPECTIVES', reviewsTitle:'The things that stay with you.', reviewSource:'Airbnb snapshot · September 17, 2026', reviewCount:'reviews at the time of capture', reviewSummary:'Editorial summaries of public Airbnb reviews; not direct quotations.', readReviews:'Read the original reviews on Airbnb',
  reviews:[['Aaron','Family stay','Memorable views, everything the group needed, and thoughtful help before and throughout the trip.'],['Maureen','Family stay','Spacious rooms, a well-equipped kitchen, and a peaceful setting with an exceptional ocean view.'],['Elliot','Family stay','Room for eight to gather, dine outdoors, and make the terrace a favorite place to relax.'],['Kelly','Group trip','Beautiful views, a clean pool, comfortable interiors, and attentive hosting from arrival to departure.']],
  hostLabel:'YOUR HOSTS', hostTitle:'A warm welcome,\nwith local knowledge.', hostText:'Roxana is your host, with Jorge as co-host. English and Spanish are spoken. For questions about the villa or help planning your stay, connect through the Airbnb listing.', hostAction:'Meet your hosts on Airbnb',
  importantLabel:'BEFORE YOU ARRIVE', importantTitle:'Island living, thoughtfully planned.', important:['The villa uses collected rainwater. Please conserve water during your stay.','There is no backup generator; temporary power interruptions may occur.','The pool is unfenced, shallow and has no lifeguard. Adult supervision is essential. No glass or diving.','Stairs and elevated terraces are part of the property. Wildlife and tropical insects may be present.','Outdoor security cameras are disclosed. Ask the host about their locations and coverage before booking.','Only registered guests are permitted. No pets, unauthorized parties or events, or smoking.'],
  faqTitle:'A few things to know.', faqs:[['When are check-in and check-out?','Check-in is after 3 pm; check-out is before 11 am. Self check-in uses a smart lock.'],['Is the pool heated?','Yes. The temperature is preset and cannot be adjusted by guests.'],['Is the entire home private?','The home is reserved for your group. Maintenance staff may occasionally access outdoor and green areas.'],['Can children stay?','Please confirm the current age policy and suitability of the pool, stairs and terraces directly with the host before booking.'],['What safety equipment is provided?','A first-aid kit is listed. Smoke and carbon monoxide detectors were not reported in the source; confirm their current status with the host.'],['Is the dock included?','No. Dock access is optional, subject to availability, prior approval and an additional fee. Ask the host about access and vessel requirements.'],['What are the rates and cancellation policy?','Current prices, availability, minimum stays and cancellation conditions are shown on Airbnb for your selected dates.']],
  finalLabel:'YOUR CULEBRA CHAPTER', finalTitle:'Leave a little room\nfor island time.', finalText:'Find your dates. Bring your people. Make yourself at home.', footer:'A private island stay in Culebra, Puerto Rico.', top:'Back to top', notFound:'This page has drifted away.', home:'Return to the villa', title:'Villa Tortuga | Private Oceanview Villa in Culebra', description:'A private four-bedroom villa in Culebra, Puerto Rico, for up to 10 guests. Panoramic ocean views, a heated pool and room to unwind near Zoni Beach.'
 },
 es: {
  skip:'Saltar al contenido', nav:['La villa','Espacios','Galería','Culebra','Tu estadía'], book:'Consultar disponibilidad en Airbnb', shortBook:'Consultar disponibilidad', external:'abre Airbnb en una pestaña nueva', language:'English', menu:'Menú', close:'Cerrar',
  eyebrow:'UNA VILLA PRIVADA · CULEBRA, PUERTO RICO', hero:'Un poco más cerca\ndel horizonte.', heroText:'Vistas al mar. Días sin prisa. Un lugar solo para ustedes.', explore:'Conocer la villa', facts:['Huéspedes','Dormitorios','Camas','Baños'],
  introLabel:'BIENVENIDOS A VILLA TORTUGA', introTitle:'Una escapada a la isla.\nEspacio para todos.', intro:'Sobre las aguas azules de Culebra, una casa pensada para compartir. Terrazas abiertas, habitaciones luminosas y una piscina privada climatizada invitan a disfrutar de otro ritmo.', introSmall:'Cuatro dormitorios en dos niveles. Espacios para reunirse y un rincón tranquilo para cada quien.',
  poolLabel:'AL AIRE LIBRE, A SU RITMO', poolTitle:'La vista siempre\nles acompaña.', poolText:'Un baño por la mañana. Un almuerzo largo junto a la piscina. Café en el balcón superior, con el mar de fondo. Aquí, los mejores planes dejan espacio para no hacer nada.', poolDetail:'Piscina privada climatizada · Terrazas panorámicas · Comedor exterior',
  roomLabel:'DESCANSAR SE SIENTE NATURAL', roomTitle:'Cuatro habitaciones.\nSu propia tranquilidad.', roomIntro:'Dos camas king y tres queen, distribuidas para recibir hasta diez huéspedes. Todos los dormitorios cuentan con aire acondicionado y Smart TV.',
  rooms:[['La suite principal','NIVEL PRINCIPAL · CAMA KING','Baño privado y una terraza propia.'],['Dormitorio dos','NIVEL PRINCIPAL · CAMA KING','Espacio para descansar. Comparte el baño completo del pasillo con el dormitorio tres.'],['Dormitorio tres','NIVEL PRINCIPAL · CAMA QUEEN','Un refugio tranquilo. Comparte el baño completo del pasillo con el dormitorio dos.'],['El refugio de la planta baja','PLANTA BAJA · DOS CAMAS QUEEN','Baño privado, kitchenette y terraza privada.']],
  kitchenLabel:'BUENA COMIDA, BUENA COMPAÑÍA', kitchenTitle:'Quédense en casa.\nCocinen juntos.', kitchenText:'La cocina completa, las cafeteras y los artículos básicos para cocinar hacen fácil sentirse en casa. Compartan en la isla de cocina, coman adentro o lleven la cena a la mesa exterior para ocho personas.',
  galleryLabel:'UNA MIRADA MÁS CERCANA', galleryTitle:'Imaginen sus días aquí.', galleryText:'Recorran los espacios, desde el primer café hasta la última mirada al mar.', all:'Todos los espacios', more:'Ver más fotos', view:'Abrir foto', previous:'Foto anterior', next:'Foto siguiente', galleryClose:'Cerrar galería', photo:'Foto', of:'de', imageError:'Esta foto no está disponible. Continúa a la siguiente.',
  amenitiesLabel:'TODO EN SU LUGAR', amenitiesTitle:'Comodidad para quedarse.', amenitiesMore:'Ver todas las comodidades',
  amenityGroups:[['Comodidad diaria','Aire acondicionado','Wi-Fi','Smart TVs y sistema de sonido','Juegos de mesa'],['Cocina y comedor','Cocina completa y lavaplatos','Cafeteras de espresso y goteo','Utensilios y vajilla','Comedor exterior y BBQ'],['Viajen más ligeros','Lavadora y secadora','Ropa de cama y toallas','Secador y artículos de baño','Sillas de playa y neverita portátil'],['Llegar es sencillo','Estacionamiento gratuito','Check-in con cerradura inteligente','Entrada privada','Balcones y terrazas privados']],
  locationLabel:'18° NORTE. OTRO RITMO.', locationTitle:'Una pequeña isla.\nOtro mundo.', locationText:'Las colinas verdes y el mar abierto de Culebra enmarcan su estadía. Visiten Playa Zoni, recorran la isla o simplemente vuelvan a disfrutar de su propia vista.', zoni:'Playa Zoni', zoniTime:'Unos 6 minutos', town:'El pueblo', townTime:'Unos 15–18 minutos', locationNote:'Tiempos aproximados indicados en el anuncio de Airbnb. Se recomienda alquilar un vehículo. La dirección exacta se comparte con huéspedes confirmados.',
  extrasTitle:'Una estadía a su manera.', extrasText:'Consulten con anticipación por paseos en bote, snorkeling guiado, buceo introductorio, masajes, yoga privado, abastecimiento de alimentos y limpieza. También puede haber acceso opcional a un muelle privado. Todo requiere coordinación previa, disponibilidad confirmada y cargos adicionales.',
  reviewsLabel:'EXPERIENCIAS DE HUÉSPEDES', reviewsTitle:'Lo que se queda con ustedes.', reviewSource:'Datos de Airbnb · 17 de septiembre de 2026', reviewCount:'reseñas al momento de la captura', reviewSummary:'Síntesis editoriales de reseñas públicas de Airbnb; no son citas textuales.', readReviews:'Leer las reseñas originales en Airbnb',
  reviews:[['Aaron','Estadía familiar','Vistas memorables, todo lo necesario para el grupo y atención antes y durante el viaje.'],['Maureen','Estadía familiar','Habitaciones amplias, cocina bien equipada y un entorno tranquilo con una vista excepcional al mar.'],['Elliot','Estadía familiar','Espacio para que ocho personas compartan, coman al aire libre y disfruten la terraza como su rincón favorito.'],['Kelly','Viaje grupal','Vistas hermosas, piscina limpia, interiores cómodos y atención desde la llegada hasta la salida.']],
  hostLabel:'SUS ANFITRIONES', hostTitle:'Una bienvenida cálida,\ncon conocimiento local.', hostText:'Roxana es la anfitriona y Jorge el coanfitrión. Hablan inglés y español. Para consultar sobre la villa o planificar su estadía, contáctenlos mediante el anuncio de Airbnb.', hostAction:'Conocer a los anfitriones en Airbnb',
  importantLabel:'ANTES DE LLEGAR', importantTitle:'La vida en la isla, bien preparada.', important:['La villa utiliza agua de lluvia recolectada. Les pedimos conservar agua durante la estadía.','No hay generador de respaldo; pueden ocurrir interrupciones eléctricas temporales.','La piscina no tiene verja ni salvavidas y es poco profunda. La supervisión adulta es esencial. No se permite vidrio ni lanzarse de cabeza.','Hay escaleras y terrazas elevadas. Puede haber fauna local e insectos tropicales.','Se declaran cámaras de seguridad exteriores. Consulten su ubicación y cobertura antes de reservar.','Solo se permiten huéspedes registrados. No se aceptan mascotas, fiestas o eventos no autorizados, ni fumar.'],
  faqTitle:'Algunas cosas que saber.', faqs:[['¿Cuáles son los horarios de entrada y salida?','La entrada es después de las 3 p. m. y la salida antes de las 11 a. m. El check-in autónomo utiliza una cerradura inteligente.'],['¿La piscina es climatizada?','Sí. La temperatura está preconfigurada y los huéspedes no pueden ajustarla.'],['¿La casa es completamente privada?','La casa queda reservada para su grupo. El personal de mantenimiento puede acceder ocasionalmente a áreas exteriores y verdes.'],['¿Pueden hospedarse niños?','Antes de reservar, confirmen con la anfitriona la política de edad vigente y si la piscina, escaleras y terrazas son adecuadas para su grupo.'],['¿Qué equipo de seguridad hay?','Se indica un botiquín de primeros auxilios. La fuente no reporta detectores de humo ni monóxido de carbono; confirmen su estado actual con la anfitriona.'],['¿El muelle está incluido?','No. Es opcional, sujeto a disponibilidad, aprobación previa y un cargo adicional. Consulten el acceso y los requisitos de la embarcación.'],['¿Cuáles son las tarifas y la política de cancelación?','Airbnb muestra los precios, disponibilidad, estadía mínima y condiciones de cancelación vigentes para las fechas seleccionadas.']],
  finalLabel:'SU PRÓXIMA HISTORIA EN CULEBRA', finalTitle:'Dejen espacio\npara la vida en la isla.', finalText:'Elijan sus fechas. Reúnan a los suyos. Siéntanse en casa.', footer:'Una estadía privada en Culebra, Puerto Rico.', top:'Volver arriba', notFound:'Esta página se fue con la marea.', home:'Volver a la villa', title:'Villa Tortuga | Villa privada con vista al mar en Culebra', description:'Villa privada de cuatro dormitorios en Culebra, Puerto Rico, para hasta 10 huéspedes. Vistas panorámicas, piscina climatizada y descanso cerca de Playa Zoni.'
 }
} as const;
export type Copy = typeof copy[Locale];
